server:
  port: 8111

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 5
      idle-timeout: 600000
      pool-name: java-rocketmq
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/dis_lock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456a?
  redis:
    host: 127.0.0.1
    database: 4
    port: 6379
    pool:
      max-active: 8
      max-wait: 01
      max-idle: 20
      min-idle: 1
    timeout: 1000
    max-total: 300s

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:com/jinfour/rocketmq/mapping/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.jinfour.rocketmq.**  # 注意：对应实体类的路径
